# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Mage Traning App"
client_id = "844e019bca8308b8d2d83e8cc92c1e5b"
application_url = "https://at-mistakes-ant-lyric.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://at-mistakes-ant-lyric.trycloudflare.com/auth/shopify/callback",
  "https://at-mistakes-ant-lyric.trycloudflare.com/authSa/shopify/callback",
  "https://at-mistakes-ant-lyric.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "training-phucvh.myshopify.com"
